spring:
  application:
    name: mydubbo-provider
server:
  port: 9999
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.meng.dubboprovider

logging:
  level:
    root: info
#    com.meng.daily.mysql.mapper: debug

